#配置redis信息
spring:
  redis:
    host: 192.168.163.129
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
  application:
    name: sendmsg-service
#  cloud:
#    nacos:
#      server-addr: localhost:8848 #nacos的地址
server:
  port: 8083