server:
  port: 8082
fastcab:
  jwt:
    enabled: true   # 是否开启JWT登录认证功能
    expiration: 3600000  # JWT 令牌的有效期，用于校验JWT令牌的合法性，单位毫秒
spring:
  application:
    name: jwt-service
#  cloud:
#    nacos:
#      server-addr: localhost:8848 #nacos的地址